### ISSUE TITLE
Missing dependencies after installation (wnck)

### ISSUE THREAD

**Issue by Crystal4276** [arcolinux/arcolinux-logout#16]
Installation of arcolinux-logout using paru on Arch Linux
current version: arcolinux-logout-22.05_27-1

Starting archlinux-logout provides this error.
```
❯ archlinux-logout
Traceback (most recent call last):
  File "/usr/share/archlinux-logout/archlinux-logout.py", line 16, in <module>
    gi.require_version('Wnck', '3.0')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Wnck not available
```
Installing manually : extra/libwnck3 43.0-2 allow the program to start

**Comment by Crystal4276** [comment]
Sorry i realize it's AUR issue. Best
