### ISSUE TITLE
arcolinux-logout log out button not working

### ISSUE THREAD

**Issue by vesaliuz** [arcolinux/arcolinux-logout#2]
Latest version of arcolinux-logout-git stop working after yesterday update.
Output:
$ arcolinux-logout
Your desktop is default
Traceback (most recent call last):   <===== Click on Log Out icon
  File "/usr/lib/arcologout/arcologout.py", line 254, in on_click
    self.click_button(widget, data)
  File "/usr/lib/arcologout/arcologout.py", line 283, in click_button
    self.__exec_cmd(command)
  File "/usr/lib/arcologout/arcologout.py", line 344, in __exec_cmd
    fn.os.system(cmdline)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by arcolinuxz** [comment]
Jon us on the forum.

Works just fine on an up to date xfce
We need to know more info.
